export const meta = {
  name: 'confirm-opus55-repeat-invalid',
  description: 'Confirmatory study: repeat Claude Opus 5.5 reads that failed the per-read audit (protocol section 5)',
  phases: [{ title: 'Repeat', detail: 'new instance, identical prompt' }],
}
const ITEMS = [{"label": "r:E064#r5", "prompt": "You are performing a blinded radiological image-reading task. You have NO access to any ground truth or label. Do NOT read any CSV, JSON, or other project file — use ONLY the images described. Base your answer solely on what you visually observe.\n\nOpen and visually examine ALL 74 axial slice images (CONTIGUOUS, caudal -> cranial through the heart — no slices are skipped) in this directory:\nC:\\Users\\Usuario\\Documents\\Investigacion\\Articulos originales\\CAC_confirm_reader_package\\images\\full\\E064\\\nnamed slice_000.png, slice_001.png, ... through slice_073.png (zero-padded THREE digits, 74 files total). Read every one of them.\n\nTASK INSTRUCTIONS:\n\nYou are evaluating axial slices from a NON-CONTRAST low-dose chest CT (LDCT) for lung cancer screening. No intravenous contrast. Standard mediastinal window (WW=350/WL=40).\n\nKEY IMAGING FACT: On this NON-CONTRAST scan, blood and non-calcified vessel walls appear GRAY. Any sharply BRIGHT/WHITE structure (as bright as bone) within the heart or along the coronary course represents CALCIUM. Do not dismiss bright intracardiac foci as contrast/vessels. Equally, do not invent calcium where the heart is uniformly gray.\n\nCAC = calcium in the walls of LM, LAD (anterior interventricular groove), LCx (left AV groove), RCA (right AV groove); LM/proximal LAD/LCx near the aortic root. CAC is NOT aortic valve/mitral/pericardial/thoracic-aorta-wall/pulmonary-vessel/granuloma/bone/costal-cartilage calcium (list under alternative_findings).\n\nHOW TO SCORE:\nStep 1. Examine each coronary (LM, LAD, LCx, RCA) across the series; note absent / isolated flecks / dense-continuous, and on how many slices. Because the slices are contiguous, a calcified vessel will appear on several consecutive slices — follow it.\nStep 2. Count vessels involved (N).\nStep 3. Integrate the WHOLE series (CAC-DRS visual ordinal):\n  - NONE -> \"0\": no coronary calcium.\n  - MILD -> \"1-100\": isolated flecks (small, sparse, one vessel, few slices).\n  - MODERATE -> \"101-300\": more than flecks; 1-2 vessels with definite calcium over several slices.\n  - SEVERE -> \">300\": continuous/dense deposits, extensive, often multiple vessels, many slices.\n\nCALIBRATION: Do not anchor on a single focus. Dense, continuous, or multi-vessel calcium over several slices is SEVERE (>300), not mild. Isolated faint specks are MILD (not NONE). Bone/cartilage/aortic-wall calcium is not CAC.\n\nReturn your assessment as the structured object.\n\nReading-harness requirement (not part of the clinical instructions): before answering, open every one of the 74 files above with the Read tool; you may issue many Read calls in a single turn. Do not open any other file or directory and do not use any other tool."}]
const SCHEMA = {"type": "object", "additionalProperties": false, "properties": {"cac_present": {"type": "boolean"}, "cac_severity": {"type": "string", "enum": ["NONE", "MILD", "MODERATE", "SEVERE"]}, "cac_locations": {"type": "array", "items": {"type": "string"}}, "n_vessels_involved": {"type": "integer"}, "agatston_category_estimated": {"type": "string", "enum": ["0", "1-100", "101-300", ">300"]}, "confidence": {"type": "string", "enum": ["HIGH", "MEDIUM", "LOW"]}, "alternative_findings": {"type": "array", "items": {"type": "string"}}, "image_quality_flag": {"type": "string", "enum": ["ADEQUATE", "LIMITED", "NON_DIAGNOSTIC"]}, "reasoning": {"type": "string"}}, "required": ["cac_present", "cac_severity", "cac_locations", "n_vessels_involved", "agatston_category_estimated", "confidence", "alternative_findings", "image_quality_flag", "reasoning"]}
phase('Repeat')
const res = await parallel(ITEMS.map(it => () => agent(it.prompt, { schema: SCHEMA, model: 'opus', agentType: 'Explore', label: 'retry1:' + it.label, phase: 'Repeat' })
  .then(r => r ? { label: it.label, ...r } : null)))
return res.filter(Boolean)
